Podio.API.Examples.MVC3/Controllers/ItemController.cs
using Podio.API.Model;
using Podio.API.Services;
using Podio.API.Utils.ApplicationFields;
using Podio.API.Utils.ItemFields;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Podio.API.Examples.MVC3.Controllers
{
    public class ItemController : Controller
    {
        public Client Client { get; set; }
        public Podio.API.Model.Application Application { get; set; }
        public Podio.API.Model.Item Item { get; set; }

        //
        // GET: /Item/Create
        [LoadClient(Order = 1), LoadApp(Order = 2)]
        public ActionResult Create()
        {
            return View(this.Application);
        }

        //
        // POST: /Item/Create

        [HttpPost, LoadClient(Order = 1), LoadApp(Order = 2)]
        public ActionResult Create(FormCollection collection)
        {
            var item = new Item();
            applyFieldValues(item, collection);

            this.Client.ItemService.AddNewItem((int)this.Application.AppId, item);
            return RedirectToRoute(new { controller = "Samples", action = "Index" });
        }

        //
        // GET: /Item/Update/1
        [LoadClient(Order = 1), LoadItem(Order = 2)]
        public ActionResult Update()
        {
            ViewData["app"] = this.Application;
            ViewData["item"] = this.Item;
            return View();
        }

        [HttpPut, LoadClient(Order = 1), LoadItem(Order = 2)]
        public ActionResult Update(FormCollection collection)
        {
            var item = new Item();
            item.ItemId = this.Item.ItemId;
            applyFieldValues(item, collection);
            this.Client.ItemService.UpdateItem(item);
            return RedirectToRoute(new { controller = "Samples", action = "Index" });
        }

        [HttpDelete, LoadClient]
        public ActionResult Delete(int itemId)
        {
            this.Client.ItemService.DeleteItem(itemId);
            return RedirectToRoute(new { controller = "Samples", action = "Index" });
        }

        private void applyFieldValues(Podio.API.Model.Item item, FormCollection collection)
        {
            foreach (var appField in Application.Fields)
            {
                var rawValue = collection[appField.ExternalId];
                if (!String.IsNullOrEmpty(rawValue) || appField.Type == "image")
                {
                    switch (appField.Type)
                    {
                        case "text":
                            var textField = item.Field<TextItemField>(appField.ExternalId);
                            textField.Value = rawValue;
                            break;
                        case "app":
                            var appRefField = item.Field<AppItemField>(appField.ExternalId);
                            appRefField.ItemIds = rawValue.Split(',').Select(id => int.Parse(id));
                            break;
                        case "contact":
                            var contactField = item.Field<ContactItemField>(appField.ExternalId);
                            contactField.ContactIds = rawValue.Split(',').Select(id => int.Parse(id));
                            break;
                        case "location":
                            var locationField = item.Field<LocationItemField>(appField.ExternalId);
                            locationField.Locations = new List<string>(rawValue.Split(','));
                            break;
                        case "duration":
                            var durationField = item.Field<DurationItemField>(appField.ExternalId);
                            durationField.Value = TimeSpan.FromSeconds(Int64.Parse(rawValue));
                            break;
                        case "progress":
                            var progressField = item.Field<ProgressItemField>(appField.ExternalId);
                            progressField.Value = int.Parse(rawValue);
                            break;
                        case "money":
                            var currency = collection[appField.ExternalId + "_currency"];
                            if (!String.IsNullOrEmpty(currency))
                            {
                                var moneyField = item.Field<MoneyItemField>(appField.ExternalId);
                                moneyField.ExternalId = appField.ExternalId;
                                moneyField.Value = int.Parse(rawValue);
                                moneyField.Currency = currency;
                            }
                            break;
                        case "date":
                            var dateField = item.Field<DateItemField>(appField.ExternalId);
                            dateField.Start = DateTime.Parse(rawValue);
                            var endString = collection[appField.ExternalId + "_end"];
                            if (!String.IsNullOrEmpty(endString))
                            {
                                dateField.End = DateTime.Parse(endString);
                            }
                            break;
                        case "question":
                        case "category":
                            var categoryAppField = Application.Field<CategoryApplicationField>(appField.ExternalId);
                            var categoryItemField = item.Field<CategoryItemField>(appField.ExternalId);
                            if (categoryAppField.Multiple)
                            {
                                categoryItemField.OptionIds = rawValue.Split(',').Select(id => int.Parse(id));
                            }
                            else
                            {
                                categoryItemField.OptionId = int.Parse(rawValue);
                            }
                            break;
                        case "embed":
                            var embedField = item.Field<EmbedItemField>(appField.ExternalId);
                            var embedUrls = new List<string>(rawValue.Split(','));
                            foreach (var embedUrl in embedUrls)
                            {
                                var embed = this.Client.EmbedService.AddAnEmbed(embedUrl.Trim());
                                if (embed.Files.Count > 0)
                                {
                                    embedField.AddEmbed((int)embed.EmbedId, embed.Files.First().FileId);
                                }
                                else
                                {
                                    embedField.AddEmbed((int)embed.EmbedId);
                                }
                            }
                            break;
                        case "image":
                            // This will break if app has more than one image field - each will get all the uploaded images
                            var fileIds = new List<int>();
                            foreach (string requestFile in Request.Files)
                            {
                                HttpPostedFileBase file = Request.Files[requestFile];
                                if (file.ContentLength > 0)
                                {
                                    byte[] data = new byte[file.ContentLength];
                                    file.InputStream.Read(data, 0, file.ContentLength);
                                    FileAttachment fileAttachment = this.Client.FileService.UploadFile(data, file.FileName, file.ContentType);
                                    fileIds.Add((int)fileAttachment.FileId);
                                }
                            }

                            if (fileIds.Count > 0)
                            {
                                var imageField = item.Field<ImageItemField>(appField.ExternalId);
                                imageField.FileIds = fileIds;
                            }
                            break;
                        case "state":
                            var stateItemField = item.Field<StateItemField>(appField.ExternalId);
                            stateItemField.Value = rawValue;
                            break;
                    }
                }
            }
        }

        private class LoadClientAttribute : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {
                if (!Podio.API.Examples.MVC3.Application.CurrentConnectionDetails.IsReadyToRubmble)
                {
                    filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new { action = "Index", controller = "Authorization" }));
                }

                var client = Podio.API.Examples.MVC3.Application.CurrentConnectionDetails.GetClient();
                ((ItemController)filterContext.Controller).Client = client;
            }
        }

        private class LoadAppAttribute : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {
                Podio.API.Model.Application app = ((ItemController)filterContext.Controller).Client.ApplicationService.GetApp(Int32.Parse(filterContext.HttpContext.Request.QueryString["app_id"]));
                ((ItemController)filterContext.Controller).Application = app;
            }
        }

        private class LoadItemAttribute : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {

Podio.API.Examples.MVC3/Views/Item/Create.cshtml
@using System.Web.Mvc.Html;
@{
    ViewBag.Title = "Item Create";
}

@{
    var app = (Podio.API.Model.Application)Model;
}

<div class="page-header">
    <h1>Create new @app.Config["item_name"]</h1>
</div>


<div class="well">
    @using (Html.BeginForm("Create", "Item", new { app_id = app.AppId }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.Partial("_Form", (Podio.API.Model.Application)Model)
        <button type="submit" class="btn btn-primary" value="Create">Create Item</button>
    }
</div>

Podio.API.Examples.MVC3/Views/Item/Update.cshtml
@using System.Web.Mvc.Html;
@{
    var item = (Podio.API.Model.Item)ViewData["item"];
    var app = (Podio.API.Model.Application)ViewData["app"];
    ViewBag.Title = "Item Update: " + item.Title;
}

<div class="page-header">
    <h1>Edit @item.Title</h1>
    <p><i><b>Notice:</b> This form is not prepopulated with the existing values of the item. Any field you change will be updated, any you leave blank will keep their current value.</i></p>
</div>


<div class="well">
    @using (Html.BeginForm("Update", "Item", new { id = item.ItemId }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HttpMethodOverride(HttpVerbs.Put)
        @Html.Partial("_Form", app)
        <button type="submit" class="btn btn-primary" value="Update">Update Item</button>
    }
</div>

Podio.API.Examples.MVC3/Views/Item/_Form.cshtml
@{
    var app = (Podio.API.Model.Application)Model;
}
@foreach (var appField in app.Fields)
{
    <label>@appField.Label (@appField.Type)</label>
    switch (appField.Type)
    {
        case "duration":
            <input type="text" name="@appField.ExternalId" /> <span>seconds</span>
            break;
        case "progress":
            <input type="text" name="@appField.ExternalId" /> <span>%</span>
            break;
        case "text":
            switch (app.Field<Podio.API.Utils.ApplicationFields.TextApplicationField>(appField.ExternalId).Size)
            {
                case "large":
                    <textarea name="@appField.ExternalId"></textarea>
                    break;
                default:
                    <input type="text" name="@appField.ExternalId" />
                    break;
            }
            break;                
        case "app":
            <input type="text" name="@appField.ExternalId" /> <span>(enter item ids separated by commas)</span>
            break;
        case "contact":
            <input type="text" name="@appField.ExternalId" /> <span>(enter profile ids separated by commas)</span>
            break;
        case "location":
            <input type="text" name="@appField.ExternalId" /> <span>(enter addresses seperated by comma)</span>
            break;                
        case "date":
            <p>Start date: <input type="text" name="@(appField.ExternalId)" /> <span>(must be parsable by DateTime.parse)</span></p>
            <p>End date: <input type="text" name="@(appField.ExternalId)_end" /> <span>(optional)</span></p>
            break; 
        case "money":
            <p>Amount: <input type="text" name="@(appField.ExternalId)" /></p>
            <p>Currency: <input type="text" name="@(appField.ExternalId)_currency" /></p>
            break;
        case "category":
        case "question":
            var categoryField = app.Field<Podio.API.Utils.ApplicationFields.CategoryApplicationField>(appField.ExternalId);
            <select @(categoryField.Multiple ? "multiple=\"multiple\"" : "" ) name="@(appField.ExternalId)">
                @foreach (var option in categoryField.Options)
	            {
		            <option value="@option.Id">@option.Text</option>
	            }
            </select>
            break;
        case "embed":
            <input type="text" name="@appField.ExternalId" /> <span>(enter urls seperated by comma)</span>
            break;                              
        case "image":
            <input type="file" name="@appField.ExternalId" />
            break;                              
        case "state":
            var stateField = app.Field<Podio.API.Utils.ApplicationFields.StateApplicationField>(appField.ExternalId);
            <select name="@(appField.ExternalId)">
                @foreach (var option in stateField.AllowedValues)
	            {
		            <option value="@option">@option</option>
	            }
            </select>
            break;
        default:
            <p><i>Not implemented yet in this sample app</i></p>
            break;
    }
}